apiVersion: v1
kind: Service
metadata:
  name: runner-web
  labels:
    app: runner
spec:
  type: ClusterIP
  ports:
    - name: front
      protocol: TCP
      port: 5000
  selector:
    app: runner
