apiVersion: apps/v1
kind: Deployment
metadata:
  name: get-pods
  labels:
    app: get-pods
spec:
  replicas: 3
  selector:
    matchLabels:
      app: get-pods
  template:
    metadata:
      labels:
        app: get-pods
    spec:
      containers:
      - name: get-pods
        image: registry1:5000/get-pods
        ports:
        - containerPort: 5000
          name: get-pods-web
        resources:
          limits:
            cpu: "100m"
            memory: "100Mi"
          requests:
            cpu: "50m"
            memory: "50Mi"
