apiVersion: v1
kind: Service
metadata:
  name: get-pods-web
  labels:
    app: get-pods
spec:
  type: ClusterIP
  ports:
    - name: front
      protocol: TCP
      port: 5000
  selector:
    app: get-pods
