apiVersion: v1
kind: Service
metadata:
  name: logger
  labels:
    app: logger
spec:
  type: NodePort
  ports:
    - name: logger-web
      protocol: TCP
      port: 5000
      nodePort: 30000
  selector:
    app: logger
